// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cloud/planton/apis/code2cloud/v1/grafanainstance/stack/kubernetes/service/stack.proto

package service

import (
	context "context"
	model "github.com/plantoncloud/planton-cloud-apis/zzgo/cloud/planton/apis/code2cloud/v1/grafanainstance/stack/kubernetes/model"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GrafanaInstanceKubernetesStackController_Execute_FullMethodName         = "/cloud.planton.apis.code2cloud.v1.grafanainstance.stack.kubernetes.service.GrafanaInstanceKubernetesStackController/execute"
	GrafanaInstanceKubernetesStackController_GetStackOutputs_FullMethodName = "/cloud.planton.apis.code2cloud.v1.grafanainstance.stack.kubernetes.service.GrafanaInstanceKubernetesStackController/getStackOutputs"
)

// GrafanaInstanceKubernetesStackControllerClient is the client API for GrafanaInstanceKubernetesStackController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrafanaInstanceKubernetesStackControllerClient interface {
	Execute(ctx context.Context, in *model.GrafanaInstanceKubernetesStackInput, opts ...grpc.CallOption) (GrafanaInstanceKubernetesStackController_ExecuteClient, error)
	GetStackOutputs(ctx context.Context, in *model.GrafanaInstanceKubernetesStackInput, opts ...grpc.CallOption) (*model.GrafanaInstanceKubernetesStackOutputs, error)
}

type grafanaInstanceKubernetesStackControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrafanaInstanceKubernetesStackControllerClient(cc grpc.ClientConnInterface) GrafanaInstanceKubernetesStackControllerClient {
	return &grafanaInstanceKubernetesStackControllerClient{cc}
}

func (c *grafanaInstanceKubernetesStackControllerClient) Execute(ctx context.Context, in *model.GrafanaInstanceKubernetesStackInput, opts ...grpc.CallOption) (GrafanaInstanceKubernetesStackController_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrafanaInstanceKubernetesStackController_ServiceDesc.Streams[0], GrafanaInstanceKubernetesStackController_Execute_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &grafanaInstanceKubernetesStackControllerExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrafanaInstanceKubernetesStackController_ExecuteClient interface {
	Recv() (*model.GrafanaInstanceKubernetesStackResponse, error)
	grpc.ClientStream
}

type grafanaInstanceKubernetesStackControllerExecuteClient struct {
	grpc.ClientStream
}

func (x *grafanaInstanceKubernetesStackControllerExecuteClient) Recv() (*model.GrafanaInstanceKubernetesStackResponse, error) {
	m := new(model.GrafanaInstanceKubernetesStackResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grafanaInstanceKubernetesStackControllerClient) GetStackOutputs(ctx context.Context, in *model.GrafanaInstanceKubernetesStackInput, opts ...grpc.CallOption) (*model.GrafanaInstanceKubernetesStackOutputs, error) {
	out := new(model.GrafanaInstanceKubernetesStackOutputs)
	err := c.cc.Invoke(ctx, GrafanaInstanceKubernetesStackController_GetStackOutputs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrafanaInstanceKubernetesStackControllerServer is the server API for GrafanaInstanceKubernetesStackController service.
// All implementations should embed UnimplementedGrafanaInstanceKubernetesStackControllerServer
// for forward compatibility
type GrafanaInstanceKubernetesStackControllerServer interface {
	Execute(*model.GrafanaInstanceKubernetesStackInput, GrafanaInstanceKubernetesStackController_ExecuteServer) error
	GetStackOutputs(context.Context, *model.GrafanaInstanceKubernetesStackInput) (*model.GrafanaInstanceKubernetesStackOutputs, error)
}

// UnimplementedGrafanaInstanceKubernetesStackControllerServer should be embedded to have forward compatible implementations.
type UnimplementedGrafanaInstanceKubernetesStackControllerServer struct {
}

func (UnimplementedGrafanaInstanceKubernetesStackControllerServer) Execute(*model.GrafanaInstanceKubernetesStackInput, GrafanaInstanceKubernetesStackController_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedGrafanaInstanceKubernetesStackControllerServer) GetStackOutputs(context.Context, *model.GrafanaInstanceKubernetesStackInput) (*model.GrafanaInstanceKubernetesStackOutputs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStackOutputs not implemented")
}

// UnsafeGrafanaInstanceKubernetesStackControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrafanaInstanceKubernetesStackControllerServer will
// result in compilation errors.
type UnsafeGrafanaInstanceKubernetesStackControllerServer interface {
	mustEmbedUnimplementedGrafanaInstanceKubernetesStackControllerServer()
}

func RegisterGrafanaInstanceKubernetesStackControllerServer(s grpc.ServiceRegistrar, srv GrafanaInstanceKubernetesStackControllerServer) {
	s.RegisterService(&GrafanaInstanceKubernetesStackController_ServiceDesc, srv)
}

func _GrafanaInstanceKubernetesStackController_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(model.GrafanaInstanceKubernetesStackInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrafanaInstanceKubernetesStackControllerServer).Execute(m, &grafanaInstanceKubernetesStackControllerExecuteServer{stream})
}

type GrafanaInstanceKubernetesStackController_ExecuteServer interface {
	Send(*model.GrafanaInstanceKubernetesStackResponse) error
	grpc.ServerStream
}

type grafanaInstanceKubernetesStackControllerExecuteServer struct {
	grpc.ServerStream
}

func (x *grafanaInstanceKubernetesStackControllerExecuteServer) Send(m *model.GrafanaInstanceKubernetesStackResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GrafanaInstanceKubernetesStackController_GetStackOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.GrafanaInstanceKubernetesStackInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrafanaInstanceKubernetesStackControllerServer).GetStackOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrafanaInstanceKubernetesStackController_GetStackOutputs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrafanaInstanceKubernetesStackControllerServer).GetStackOutputs(ctx, req.(*model.GrafanaInstanceKubernetesStackInput))
	}
	return interceptor(ctx, in, info, handler)
}

// GrafanaInstanceKubernetesStackController_ServiceDesc is the grpc.ServiceDesc for GrafanaInstanceKubernetesStackController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrafanaInstanceKubernetesStackController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.planton.apis.code2cloud.v1.grafanainstance.stack.kubernetes.service.GrafanaInstanceKubernetesStackController",
	HandlerType: (*GrafanaInstanceKubernetesStackControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStackOutputs",
			Handler:    _GrafanaInstanceKubernetesStackController_GetStackOutputs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "execute",
			Handler:       _GrafanaInstanceKubernetesStackController_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cloud/planton/apis/code2cloud/v1/grafanainstance/stack/kubernetes/service/stack.proto",
}
