// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cloud/planton/apis/iac/v1/stackjobrunner/service/command.proto

package service

import (
	context "context"
	model "github.com/plantoncloud/planton-cloud-apis/zzgo/cloud/planton/apis/iac/v1/stackjobrunner/model"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StackJobRunnerCommandController_Create_FullMethodName  = "/cloud.planton.apis.iac.v1.stackjobrunner.service.StackJobRunnerCommandController/create"
	StackJobRunnerCommandController_Update_FullMethodName  = "/cloud.planton.apis.iac.v1.stackjobrunner.service.StackJobRunnerCommandController/update"
	StackJobRunnerCommandController_Delete_FullMethodName  = "/cloud.planton.apis.iac.v1.stackjobrunner.service.StackJobRunnerCommandController/delete"
	StackJobRunnerCommandController_Restore_FullMethodName = "/cloud.planton.apis.iac.v1.stackjobrunner.service.StackJobRunnerCommandController/restore"
)

// StackJobRunnerCommandControllerClient is the client API for StackJobRunnerCommandController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StackJobRunnerCommandControllerClient interface {
	// create stack-job-runner
	Create(ctx context.Context, in *model.StackJobRunner, opts ...grpc.CallOption) (*model.StackJobRunner, error)
	// update stack-job-runner
	Update(ctx context.Context, in *model.StackJobRunner, opts ...grpc.CallOption) (*model.StackJobRunner, error)
	// delete stack-job-runner
	Delete(ctx context.Context, in *model.StackJobRunnerId, opts ...grpc.CallOption) (*model.StackJobRunner, error)
	// restore stack-job-runner
	Restore(ctx context.Context, in *model.StackJobRunner, opts ...grpc.CallOption) (*model.StackJobRunner, error)
}

type stackJobRunnerCommandControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewStackJobRunnerCommandControllerClient(cc grpc.ClientConnInterface) StackJobRunnerCommandControllerClient {
	return &stackJobRunnerCommandControllerClient{cc}
}

func (c *stackJobRunnerCommandControllerClient) Create(ctx context.Context, in *model.StackJobRunner, opts ...grpc.CallOption) (*model.StackJobRunner, error) {
	out := new(model.StackJobRunner)
	err := c.cc.Invoke(ctx, StackJobRunnerCommandController_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackJobRunnerCommandControllerClient) Update(ctx context.Context, in *model.StackJobRunner, opts ...grpc.CallOption) (*model.StackJobRunner, error) {
	out := new(model.StackJobRunner)
	err := c.cc.Invoke(ctx, StackJobRunnerCommandController_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackJobRunnerCommandControllerClient) Delete(ctx context.Context, in *model.StackJobRunnerId, opts ...grpc.CallOption) (*model.StackJobRunner, error) {
	out := new(model.StackJobRunner)
	err := c.cc.Invoke(ctx, StackJobRunnerCommandController_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackJobRunnerCommandControllerClient) Restore(ctx context.Context, in *model.StackJobRunner, opts ...grpc.CallOption) (*model.StackJobRunner, error) {
	out := new(model.StackJobRunner)
	err := c.cc.Invoke(ctx, StackJobRunnerCommandController_Restore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StackJobRunnerCommandControllerServer is the server API for StackJobRunnerCommandController service.
// All implementations should embed UnimplementedStackJobRunnerCommandControllerServer
// for forward compatibility
type StackJobRunnerCommandControllerServer interface {
	// create stack-job-runner
	Create(context.Context, *model.StackJobRunner) (*model.StackJobRunner, error)
	// update stack-job-runner
	Update(context.Context, *model.StackJobRunner) (*model.StackJobRunner, error)
	// delete stack-job-runner
	Delete(context.Context, *model.StackJobRunnerId) (*model.StackJobRunner, error)
	// restore stack-job-runner
	Restore(context.Context, *model.StackJobRunner) (*model.StackJobRunner, error)
}

// UnimplementedStackJobRunnerCommandControllerServer should be embedded to have forward compatible implementations.
type UnimplementedStackJobRunnerCommandControllerServer struct {
}

func (UnimplementedStackJobRunnerCommandControllerServer) Create(context.Context, *model.StackJobRunner) (*model.StackJobRunner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedStackJobRunnerCommandControllerServer) Update(context.Context, *model.StackJobRunner) (*model.StackJobRunner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedStackJobRunnerCommandControllerServer) Delete(context.Context, *model.StackJobRunnerId) (*model.StackJobRunner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStackJobRunnerCommandControllerServer) Restore(context.Context, *model.StackJobRunner) (*model.StackJobRunner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}

// UnsafeStackJobRunnerCommandControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StackJobRunnerCommandControllerServer will
// result in compilation errors.
type UnsafeStackJobRunnerCommandControllerServer interface {
	mustEmbedUnimplementedStackJobRunnerCommandControllerServer()
}

func RegisterStackJobRunnerCommandControllerServer(s grpc.ServiceRegistrar, srv StackJobRunnerCommandControllerServer) {
	s.RegisterService(&StackJobRunnerCommandController_ServiceDesc, srv)
}

func _StackJobRunnerCommandController_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.StackJobRunner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobRunnerCommandControllerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobRunnerCommandController_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobRunnerCommandControllerServer).Create(ctx, req.(*model.StackJobRunner))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackJobRunnerCommandController_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.StackJobRunner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobRunnerCommandControllerServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobRunnerCommandController_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobRunnerCommandControllerServer).Update(ctx, req.(*model.StackJobRunner))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackJobRunnerCommandController_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.StackJobRunnerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobRunnerCommandControllerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobRunnerCommandController_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobRunnerCommandControllerServer).Delete(ctx, req.(*model.StackJobRunnerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackJobRunnerCommandController_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.StackJobRunner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobRunnerCommandControllerServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobRunnerCommandController_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobRunnerCommandControllerServer).Restore(ctx, req.(*model.StackJobRunner))
	}
	return interceptor(ctx, in, info, handler)
}

// StackJobRunnerCommandController_ServiceDesc is the grpc.ServiceDesc for StackJobRunnerCommandController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StackJobRunnerCommandController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.planton.apis.iac.v1.stackjobrunner.service.StackJobRunnerCommandController",
	HandlerType: (*StackJobRunnerCommandControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _StackJobRunnerCommandController_Create_Handler,
		},
		{
			MethodName: "update",
			Handler:    _StackJobRunnerCommandController_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _StackJobRunnerCommandController_Delete_Handler,
		},
		{
			MethodName: "restore",
			Handler:    _StackJobRunnerCommandController_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud/planton/apis/iac/v1/stackjobrunner/service/command.proto",
}
