// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
//
// Source: cloud/planton/apis/v1/code2cloud/deploy/dnszone/stack/aws/service.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// dns-zone stack controller
public protocol Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackControllerClientInterface {

    @available(iOS 13, *)
    func `execute`(headers: Connect.Headers) -> any Connect.ServerOnlyAsyncStreamInterface<Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackInput, Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackResponse>

    @available(iOS 13, *)
    func `getStackOutputs`(request: Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackInput, headers: Connect.Headers) async -> ResponseMessage<Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackOutputs>
}

/// Concrete implementation of `Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackControllerClientInterface`.
public final class Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackControllerClient: Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackControllerClientInterface {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `execute`(headers: Connect.Headers = [:]) -> any Connect.ServerOnlyAsyncStreamInterface<Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackInput, Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackResponse> {
        return self.client.serverOnlyStream(path: "cloud.planton.apis.v1.code2cloud.deploy.dnszone.stack.aws.DnsZoneAwsStackController/execute", headers: headers)
    }

    @available(iOS 13, *)
    public func `getStackOutputs`(request: Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackInput, headers: Connect.Headers = [:]) async -> ResponseMessage<Cloud_Planton_Apis_V1_Code2cloud_Deploy_Dnszone_Stack_Aws_DnsZoneAwsStackOutputs> {
        return await self.client.unary(path: "cloud.planton.apis.v1.code2cloud.deploy.dnszone.stack.aws.DnsZoneAwsStackController/getStackOutputs", request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let execute = Connect.MethodSpec(name: "execute", service: "cloud.planton.apis.v1.code2cloud.deploy.dnszone.stack.aws.DnsZoneAwsStackController", type: .serverStream)
            public static let getStackOutputs = Connect.MethodSpec(name: "getStackOutputs", service: "cloud.planton.apis.v1.code2cloud.deploy.dnszone.stack.aws.DnsZoneAwsStackController", type: .unary)
        }
    }
}
