// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cloud/planton/apis/v1/stack/job/query.proto

package job

import (
	context "context"
	progress "github.com/plantoncloud/planton-cloud-apis/zzgo/cloud/planton/apis/v1/stack/job/progress"
	snapshot "github.com/plantoncloud/planton-cloud-apis/zzgo/cloud/planton/apis/v1/stack/job/progress/snapshot"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StackJobQueryController_ListByFilters_FullMethodName                     = "/cloud.planton.apis.v1.stack.job.StackJobQueryController/listByFilters"
	StackJobQueryController_GetById_FullMethodName                           = "/cloud.planton.apis.v1.stack.job.StackJobQueryController/getById"
	StackJobQueryController_GetProgressEventStream_FullMethodName            = "/cloud.planton.apis.v1.stack.job.StackJobQueryController/getProgressEventStream"
	StackJobQueryController_GetStackJobLogSnapshotStream_FullMethodName      = "/cloud.planton.apis.v1.stack.job.StackJobQueryController/getStackJobLogSnapshotStream"
	StackJobQueryController_GetStackJobMinutesMTDByCompanyId_FullMethodName  = "/cloud.planton.apis.v1.stack.job.StackJobQueryController/getStackJobMinutesMTDByCompanyId"
	StackJobQueryController_GetResourceCountByCompanyId_FullMethodName       = "/cloud.planton.apis.v1.stack.job.StackJobQueryController/getResourceCountByCompanyId"
	StackJobQueryController_GetPulumiResourceCountByCompanyId_FullMethodName = "/cloud.planton.apis.v1.stack.job.StackJobQueryController/getPulumiResourceCountByCompanyId"
)

// StackJobQueryControllerClient is the client API for StackJobQueryController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StackJobQueryControllerClient interface {
	// list of stack-jobs
	// todo: need to add authorization
	ListByFilters(ctx context.Context, in *ListStackJobsByFiltersQueryInput, opts ...grpc.CallOption) (*StackJobList, error)
	// look up stack-job by stack-job-id
	// todo: need to add authorization
	GetById(ctx context.Context, in *StackJobId, opts ...grpc.CallOption) (*StackJob, error)
	// rpc to get stack-job progress event stream
	// this rpc is required to support pulumi progress or diff view in the cli client which is an interactive client.
	GetProgressEventStream(ctx context.Context, in *StackJobId, opts ...grpc.CallOption) (StackJobQueryController_GetProgressEventStreamClient, error)
	// rpc to get snapshot of stack-job log
	// response is optimized to display the stack-job log on non-interactive client-apps
	GetStackJobLogSnapshotStream(ctx context.Context, in *StackJobId, opts ...grpc.CallOption) (StackJobQueryController_GetStackJobLogSnapshotStreamClient, error)
	// getStackJobMinutesMTBByCompanyId retrieves the total running minutes of stack jobs associated with a specific company.
	// This call is essential for systems needing to monitor, report, or bill based on the duration of stack jobs executed
	// within the context of a company. It requires a GetStackJobMinutesByCompanyIdInput message containing the company_id
	// for which the stack job minutes are being queried and returns a StackJobMinutesMTB message containing the total minutes.
	GetStackJobMinutesMTDByCompanyId(ctx context.Context, in *GetStackJobMinutesByCompanyIdInput, opts ...grpc.CallOption) (*StackJobMinutesMTD, error)
	// getResourceCountByCompanyId retrieves detailed information about the count of different resources
	// associated with a given company. The request requires a GetResourceCountByCompanyIdInput message
	// containing the company_id of interest. It returns a ResourceCount message, which includes the type
	// and name of the resource along with its total count within the specified company.
	GetResourceCountByCompanyId(ctx context.Context, in *GetResourceCountByCompanyIdInput, opts ...grpc.CallOption) (*ResourcesCount, error)
	// getPulumiResourceCountByCompanyId is an RPC that queries the total count of Pulumi resources
	// associated with a specified company. This operation requires an input of type
	// GetPulumiResourceCountByCompanyIdInput, which includes the company_id to identify the target
	// company. It returns a TotalPulumiResourceCount message, encapsulating the aggregate count of
	// Pulumi resources managed under the given company's account. This service is essential for
	// organizations utilizing Pulumi for infrastructure as code (IaC) to monitor and manage their
	// cloud resource utilization, facilitating effective resource planning, auditing, and optimization.
	GetPulumiResourceCountByCompanyId(ctx context.Context, in *GetPulumiResourceCountByCompanyIdInput, opts ...grpc.CallOption) (*TotalPulumiResourceCount, error)
}

type stackJobQueryControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewStackJobQueryControllerClient(cc grpc.ClientConnInterface) StackJobQueryControllerClient {
	return &stackJobQueryControllerClient{cc}
}

func (c *stackJobQueryControllerClient) ListByFilters(ctx context.Context, in *ListStackJobsByFiltersQueryInput, opts ...grpc.CallOption) (*StackJobList, error) {
	out := new(StackJobList)
	err := c.cc.Invoke(ctx, StackJobQueryController_ListByFilters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackJobQueryControllerClient) GetById(ctx context.Context, in *StackJobId, opts ...grpc.CallOption) (*StackJob, error) {
	out := new(StackJob)
	err := c.cc.Invoke(ctx, StackJobQueryController_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackJobQueryControllerClient) GetProgressEventStream(ctx context.Context, in *StackJobId, opts ...grpc.CallOption) (StackJobQueryController_GetProgressEventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StackJobQueryController_ServiceDesc.Streams[0], StackJobQueryController_GetProgressEventStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stackJobQueryControllerGetProgressEventStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StackJobQueryController_GetProgressEventStreamClient interface {
	Recv() (*progress.StackJobProgressEvent, error)
	grpc.ClientStream
}

type stackJobQueryControllerGetProgressEventStreamClient struct {
	grpc.ClientStream
}

func (x *stackJobQueryControllerGetProgressEventStreamClient) Recv() (*progress.StackJobProgressEvent, error) {
	m := new(progress.StackJobProgressEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stackJobQueryControllerClient) GetStackJobLogSnapshotStream(ctx context.Context, in *StackJobId, opts ...grpc.CallOption) (StackJobQueryController_GetStackJobLogSnapshotStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StackJobQueryController_ServiceDesc.Streams[1], StackJobQueryController_GetStackJobLogSnapshotStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stackJobQueryControllerGetStackJobLogSnapshotStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StackJobQueryController_GetStackJobLogSnapshotStreamClient interface {
	Recv() (*snapshot.StackJobLogSnapshot, error)
	grpc.ClientStream
}

type stackJobQueryControllerGetStackJobLogSnapshotStreamClient struct {
	grpc.ClientStream
}

func (x *stackJobQueryControllerGetStackJobLogSnapshotStreamClient) Recv() (*snapshot.StackJobLogSnapshot, error) {
	m := new(snapshot.StackJobLogSnapshot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stackJobQueryControllerClient) GetStackJobMinutesMTDByCompanyId(ctx context.Context, in *GetStackJobMinutesByCompanyIdInput, opts ...grpc.CallOption) (*StackJobMinutesMTD, error) {
	out := new(StackJobMinutesMTD)
	err := c.cc.Invoke(ctx, StackJobQueryController_GetStackJobMinutesMTDByCompanyId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackJobQueryControllerClient) GetResourceCountByCompanyId(ctx context.Context, in *GetResourceCountByCompanyIdInput, opts ...grpc.CallOption) (*ResourcesCount, error) {
	out := new(ResourcesCount)
	err := c.cc.Invoke(ctx, StackJobQueryController_GetResourceCountByCompanyId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackJobQueryControllerClient) GetPulumiResourceCountByCompanyId(ctx context.Context, in *GetPulumiResourceCountByCompanyIdInput, opts ...grpc.CallOption) (*TotalPulumiResourceCount, error) {
	out := new(TotalPulumiResourceCount)
	err := c.cc.Invoke(ctx, StackJobQueryController_GetPulumiResourceCountByCompanyId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StackJobQueryControllerServer is the server API for StackJobQueryController service.
// All implementations should embed UnimplementedStackJobQueryControllerServer
// for forward compatibility
type StackJobQueryControllerServer interface {
	// list of stack-jobs
	// todo: need to add authorization
	ListByFilters(context.Context, *ListStackJobsByFiltersQueryInput) (*StackJobList, error)
	// look up stack-job by stack-job-id
	// todo: need to add authorization
	GetById(context.Context, *StackJobId) (*StackJob, error)
	// rpc to get stack-job progress event stream
	// this rpc is required to support pulumi progress or diff view in the cli client which is an interactive client.
	GetProgressEventStream(*StackJobId, StackJobQueryController_GetProgressEventStreamServer) error
	// rpc to get snapshot of stack-job log
	// response is optimized to display the stack-job log on non-interactive client-apps
	GetStackJobLogSnapshotStream(*StackJobId, StackJobQueryController_GetStackJobLogSnapshotStreamServer) error
	// getStackJobMinutesMTBByCompanyId retrieves the total running minutes of stack jobs associated with a specific company.
	// This call is essential for systems needing to monitor, report, or bill based on the duration of stack jobs executed
	// within the context of a company. It requires a GetStackJobMinutesByCompanyIdInput message containing the company_id
	// for which the stack job minutes are being queried and returns a StackJobMinutesMTB message containing the total minutes.
	GetStackJobMinutesMTDByCompanyId(context.Context, *GetStackJobMinutesByCompanyIdInput) (*StackJobMinutesMTD, error)
	// getResourceCountByCompanyId retrieves detailed information about the count of different resources
	// associated with a given company. The request requires a GetResourceCountByCompanyIdInput message
	// containing the company_id of interest. It returns a ResourceCount message, which includes the type
	// and name of the resource along with its total count within the specified company.
	GetResourceCountByCompanyId(context.Context, *GetResourceCountByCompanyIdInput) (*ResourcesCount, error)
	// getPulumiResourceCountByCompanyId is an RPC that queries the total count of Pulumi resources
	// associated with a specified company. This operation requires an input of type
	// GetPulumiResourceCountByCompanyIdInput, which includes the company_id to identify the target
	// company. It returns a TotalPulumiResourceCount message, encapsulating the aggregate count of
	// Pulumi resources managed under the given company's account. This service is essential for
	// organizations utilizing Pulumi for infrastructure as code (IaC) to monitor and manage their
	// cloud resource utilization, facilitating effective resource planning, auditing, and optimization.
	GetPulumiResourceCountByCompanyId(context.Context, *GetPulumiResourceCountByCompanyIdInput) (*TotalPulumiResourceCount, error)
}

// UnimplementedStackJobQueryControllerServer should be embedded to have forward compatible implementations.
type UnimplementedStackJobQueryControllerServer struct {
}

func (UnimplementedStackJobQueryControllerServer) ListByFilters(context.Context, *ListStackJobsByFiltersQueryInput) (*StackJobList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByFilters not implemented")
}
func (UnimplementedStackJobQueryControllerServer) GetById(context.Context, *StackJobId) (*StackJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedStackJobQueryControllerServer) GetProgressEventStream(*StackJobId, StackJobQueryController_GetProgressEventStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetProgressEventStream not implemented")
}
func (UnimplementedStackJobQueryControllerServer) GetStackJobLogSnapshotStream(*StackJobId, StackJobQueryController_GetStackJobLogSnapshotStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStackJobLogSnapshotStream not implemented")
}
func (UnimplementedStackJobQueryControllerServer) GetStackJobMinutesMTDByCompanyId(context.Context, *GetStackJobMinutesByCompanyIdInput) (*StackJobMinutesMTD, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStackJobMinutesMTDByCompanyId not implemented")
}
func (UnimplementedStackJobQueryControllerServer) GetResourceCountByCompanyId(context.Context, *GetResourceCountByCompanyIdInput) (*ResourcesCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceCountByCompanyId not implemented")
}
func (UnimplementedStackJobQueryControllerServer) GetPulumiResourceCountByCompanyId(context.Context, *GetPulumiResourceCountByCompanyIdInput) (*TotalPulumiResourceCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPulumiResourceCountByCompanyId not implemented")
}

// UnsafeStackJobQueryControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StackJobQueryControllerServer will
// result in compilation errors.
type UnsafeStackJobQueryControllerServer interface {
	mustEmbedUnimplementedStackJobQueryControllerServer()
}

func RegisterStackJobQueryControllerServer(s grpc.ServiceRegistrar, srv StackJobQueryControllerServer) {
	s.RegisterService(&StackJobQueryController_ServiceDesc, srv)
}

func _StackJobQueryController_ListByFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStackJobsByFiltersQueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobQueryControllerServer).ListByFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobQueryController_ListByFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobQueryControllerServer).ListByFilters(ctx, req.(*ListStackJobsByFiltersQueryInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackJobQueryController_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackJobId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobQueryControllerServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobQueryController_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobQueryControllerServer).GetById(ctx, req.(*StackJobId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackJobQueryController_GetProgressEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StackJobId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StackJobQueryControllerServer).GetProgressEventStream(m, &stackJobQueryControllerGetProgressEventStreamServer{stream})
}

type StackJobQueryController_GetProgressEventStreamServer interface {
	Send(*progress.StackJobProgressEvent) error
	grpc.ServerStream
}

type stackJobQueryControllerGetProgressEventStreamServer struct {
	grpc.ServerStream
}

func (x *stackJobQueryControllerGetProgressEventStreamServer) Send(m *progress.StackJobProgressEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _StackJobQueryController_GetStackJobLogSnapshotStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StackJobId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StackJobQueryControllerServer).GetStackJobLogSnapshotStream(m, &stackJobQueryControllerGetStackJobLogSnapshotStreamServer{stream})
}

type StackJobQueryController_GetStackJobLogSnapshotStreamServer interface {
	Send(*snapshot.StackJobLogSnapshot) error
	grpc.ServerStream
}

type stackJobQueryControllerGetStackJobLogSnapshotStreamServer struct {
	grpc.ServerStream
}

func (x *stackJobQueryControllerGetStackJobLogSnapshotStreamServer) Send(m *snapshot.StackJobLogSnapshot) error {
	return x.ServerStream.SendMsg(m)
}

func _StackJobQueryController_GetStackJobMinutesMTDByCompanyId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStackJobMinutesByCompanyIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobQueryControllerServer).GetStackJobMinutesMTDByCompanyId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobQueryController_GetStackJobMinutesMTDByCompanyId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobQueryControllerServer).GetStackJobMinutesMTDByCompanyId(ctx, req.(*GetStackJobMinutesByCompanyIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackJobQueryController_GetResourceCountByCompanyId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceCountByCompanyIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobQueryControllerServer).GetResourceCountByCompanyId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobQueryController_GetResourceCountByCompanyId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobQueryControllerServer).GetResourceCountByCompanyId(ctx, req.(*GetResourceCountByCompanyIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackJobQueryController_GetPulumiResourceCountByCompanyId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPulumiResourceCountByCompanyIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackJobQueryControllerServer).GetPulumiResourceCountByCompanyId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackJobQueryController_GetPulumiResourceCountByCompanyId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackJobQueryControllerServer).GetPulumiResourceCountByCompanyId(ctx, req.(*GetPulumiResourceCountByCompanyIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

// StackJobQueryController_ServiceDesc is the grpc.ServiceDesc for StackJobQueryController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StackJobQueryController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.planton.apis.v1.stack.job.StackJobQueryController",
	HandlerType: (*StackJobQueryControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listByFilters",
			Handler:    _StackJobQueryController_ListByFilters_Handler,
		},
		{
			MethodName: "getById",
			Handler:    _StackJobQueryController_GetById_Handler,
		},
		{
			MethodName: "getStackJobMinutesMTDByCompanyId",
			Handler:    _StackJobQueryController_GetStackJobMinutesMTDByCompanyId_Handler,
		},
		{
			MethodName: "getResourceCountByCompanyId",
			Handler:    _StackJobQueryController_GetResourceCountByCompanyId_Handler,
		},
		{
			MethodName: "getPulumiResourceCountByCompanyId",
			Handler:    _StackJobQueryController_GetPulumiResourceCountByCompanyId_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getProgressEventStream",
			Handler:       _StackJobQueryController_GetProgressEventStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getStackJobLogSnapshotStream",
			Handler:       _StackJobQueryController_GetStackJobLogSnapshotStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cloud/planton/apis/v1/stack/job/query.proto",
}
