// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cloud/planton/apis/v1/code2cloud/deploy/customendpoint/stack/kubernetes/service.proto

package kubernetes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CustomEndpointKubernetesStackController_Execute_FullMethodName         = "/cloud.planton.apis.v1.code2cloud.deploy.customendpoint.stack.kubernetes.CustomEndpointKubernetesStackController/execute"
	CustomEndpointKubernetesStackController_GetStackOutputs_FullMethodName = "/cloud.planton.apis.v1.code2cloud.deploy.customendpoint.stack.kubernetes.CustomEndpointKubernetesStackController/getStackOutputs"
)

// CustomEndpointKubernetesStackControllerClient is the client API for CustomEndpointKubernetesStackController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomEndpointKubernetesStackControllerClient interface {
	Execute(ctx context.Context, in *CustomEndpointKubernetesStackInput, opts ...grpc.CallOption) (CustomEndpointKubernetesStackController_ExecuteClient, error)
	GetStackOutputs(ctx context.Context, in *CustomEndpointKubernetesStackInput, opts ...grpc.CallOption) (*CustomEndpointKubernetesStackOutputs, error)
}

type customEndpointKubernetesStackControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomEndpointKubernetesStackControllerClient(cc grpc.ClientConnInterface) CustomEndpointKubernetesStackControllerClient {
	return &customEndpointKubernetesStackControllerClient{cc}
}

func (c *customEndpointKubernetesStackControllerClient) Execute(ctx context.Context, in *CustomEndpointKubernetesStackInput, opts ...grpc.CallOption) (CustomEndpointKubernetesStackController_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &CustomEndpointKubernetesStackController_ServiceDesc.Streams[0], CustomEndpointKubernetesStackController_Execute_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &customEndpointKubernetesStackControllerExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CustomEndpointKubernetesStackController_ExecuteClient interface {
	Recv() (*CustomEndpointKubernetesStackResponse, error)
	grpc.ClientStream
}

type customEndpointKubernetesStackControllerExecuteClient struct {
	grpc.ClientStream
}

func (x *customEndpointKubernetesStackControllerExecuteClient) Recv() (*CustomEndpointKubernetesStackResponse, error) {
	m := new(CustomEndpointKubernetesStackResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customEndpointKubernetesStackControllerClient) GetStackOutputs(ctx context.Context, in *CustomEndpointKubernetesStackInput, opts ...grpc.CallOption) (*CustomEndpointKubernetesStackOutputs, error) {
	out := new(CustomEndpointKubernetesStackOutputs)
	err := c.cc.Invoke(ctx, CustomEndpointKubernetesStackController_GetStackOutputs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomEndpointKubernetesStackControllerServer is the server API for CustomEndpointKubernetesStackController service.
// All implementations should embed UnimplementedCustomEndpointKubernetesStackControllerServer
// for forward compatibility
type CustomEndpointKubernetesStackControllerServer interface {
	Execute(*CustomEndpointKubernetesStackInput, CustomEndpointKubernetesStackController_ExecuteServer) error
	GetStackOutputs(context.Context, *CustomEndpointKubernetesStackInput) (*CustomEndpointKubernetesStackOutputs, error)
}

// UnimplementedCustomEndpointKubernetesStackControllerServer should be embedded to have forward compatible implementations.
type UnimplementedCustomEndpointKubernetesStackControllerServer struct {
}

func (UnimplementedCustomEndpointKubernetesStackControllerServer) Execute(*CustomEndpointKubernetesStackInput, CustomEndpointKubernetesStackController_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCustomEndpointKubernetesStackControllerServer) GetStackOutputs(context.Context, *CustomEndpointKubernetesStackInput) (*CustomEndpointKubernetesStackOutputs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStackOutputs not implemented")
}

// UnsafeCustomEndpointKubernetesStackControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomEndpointKubernetesStackControllerServer will
// result in compilation errors.
type UnsafeCustomEndpointKubernetesStackControllerServer interface {
	mustEmbedUnimplementedCustomEndpointKubernetesStackControllerServer()
}

func RegisterCustomEndpointKubernetesStackControllerServer(s grpc.ServiceRegistrar, srv CustomEndpointKubernetesStackControllerServer) {
	s.RegisterService(&CustomEndpointKubernetesStackController_ServiceDesc, srv)
}

func _CustomEndpointKubernetesStackController_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomEndpointKubernetesStackInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomEndpointKubernetesStackControllerServer).Execute(m, &customEndpointKubernetesStackControllerExecuteServer{stream})
}

type CustomEndpointKubernetesStackController_ExecuteServer interface {
	Send(*CustomEndpointKubernetesStackResponse) error
	grpc.ServerStream
}

type customEndpointKubernetesStackControllerExecuteServer struct {
	grpc.ServerStream
}

func (x *customEndpointKubernetesStackControllerExecuteServer) Send(m *CustomEndpointKubernetesStackResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CustomEndpointKubernetesStackController_GetStackOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomEndpointKubernetesStackInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEndpointKubernetesStackControllerServer).GetStackOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomEndpointKubernetesStackController_GetStackOutputs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEndpointKubernetesStackControllerServer).GetStackOutputs(ctx, req.(*CustomEndpointKubernetesStackInput))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomEndpointKubernetesStackController_ServiceDesc is the grpc.ServiceDesc for CustomEndpointKubernetesStackController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomEndpointKubernetesStackController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.planton.apis.v1.code2cloud.deploy.customendpoint.stack.kubernetes.CustomEndpointKubernetesStackController",
	HandlerType: (*CustomEndpointKubernetesStackControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStackOutputs",
			Handler:    _CustomEndpointKubernetesStackController_GetStackOutputs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "execute",
			Handler:       _CustomEndpointKubernetesStackController_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cloud/planton/apis/v1/code2cloud/deploy/customendpoint/stack/kubernetes/service.proto",
}
